set(SOURCE_FILES
        "src/engine/core/Log.cpp"
        "src/engine/core/Types.cpp"
        "src/engine/Engine.cpp"
        "src/engine/core/Window.cpp"
        "src/engine/vulkan/Instance.cpp"
        "src/engine/vulkan/Renderer.cpp"
        "src/engine/vulkan/Device.cpp"
        "src/engine/vulkan/Buffer.cpp"
        "src/engine/vulkan/Surface.cpp"
        "src/engine/vulkan/SwapChain.cpp"
        "src/engine/shaders/ShaderCache.cpp"
        "src/engine/shaders/CompileShader.cpp"
        "src/engine/vulkan/descriptors/DescriptorPool.cpp"
        "src/engine/vulkan/descriptors/DescriptorSetLayout.cpp"
        "src/engine/vulkan/descriptors/DescriptorWriter.cpp"
        "src/engine/entity component system/Mesh.cpp"
        )