set(SOURCE_FILES
        "src/engine/core/Log.cpp"
        "src/engine/core/Types.cpp"
        "src/engine/Engine.cpp"
        "src/engine/window/Window.cpp"
        "src/engine/vulkan/Instance.cpp"
        "src/engine/vulkan/Renderer.cpp"
        "src/engine/vulkan/Device.cpp"
        "src/engine/vulkan/Buffer.cpp"
        "src/engine/vulkan/Surface.cpp"
        "src/engine/vulkan/SwapChain.cpp"
        "src/engine/shaders/ShaderCache.cpp"
        "src/engine/shaders/CompileShader.cpp"
        "src/engine/vulkan/descriptors/DescriptorPool.cpp"
        "src/engine/vulkan/descriptors/DescriptorSetLayout.cpp"
        "src/engine/vulkan/descriptors/DescriptorWriter.cpp"
        "src/engine/entity component system/Mesh.cpp"
        "src/engine/utilities/UtilityFunctions.cpp"
        "src/engine/vulkan/CommandPool.cpp"
        "src/engine/vulkan/renderers/MeshRenderer.cpp"
        "src/engine/vulkan/Pipeline.cpp"
        "src/engine/vulkan/Batch.cpp"
        "src/engine/vulkan/MemoryAllocator.cpp"
        "src/engine/vulkan/MemoryManagement.cpp"
        "src/engine/entity component system/GameObject.cpp"
        "src/engine/entity component system/Transform.cpp"
        "src/engine/window/EventHandler.cpp"
        "src/engine/vulkan/gui/imgui/imgui.cpp"
        "src/engine/vulkan/gui/imgui/imgui_draw.cpp"
        "src/engine/vulkan/gui/imgui/imgui_tables.cpp"
        "src/engine/vulkan/gui/imgui/imgui_widgets.cpp"
        "src/engine/vulkan/gui/imgui/imgui_demo.cpp"
        "src/engine/vulkan/gui/imgui/imgui_impl_glfw.cpp"
        "src/engine/vulkan/gui/imgui/imgui_impl_vulkan.cpp"
        "src/engine/vulkan/gui/UI.cpp"
        "src/engine/vulkan/VulkanTypes.cpp"
        )

set(PrecompiledHeaders
        "src/engine/core/PrecompiledHeaders.h"
        "src/engine/vulkan/VulkanPrecompiledHeaders.h"
        )