set(SOURCE_FILES
        "src/engine/core/Log.cpp"
        "src/engine/Engine.cpp"
        "src/engine/core/Window.cpp"
        "src/engine/vulkan/Instance.cpp"
        "src/engine/vulkan/MemoryManagement.cpp"
        "src/engine/vulkan/Renderer.cpp"
        "src/engine/vulkan/Device.cpp"
        "src/engine/vulkan/Buffer.cpp"
        "src/engine/vulkan/Surface.cpp"
        "src/engine/vulkan/SwapChain.cpp"
        )